- name: "Run powershell script"
  ansible_connection: winrm
  ansible_winrm_transport: basic
  hosts: all
  gather_facts: "false"
  tasks:
    - name: "Start Windows Update"
      script: "https://github.com/trustinator/AnsibleWindows/winupdate.ps1"
